application: iepsen
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /font-awesome
  static_dir: font-awesome

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: .*
  script: portfolio.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
