baseurl                 = "https://iepsen.netlify.com/"   # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Marcelo Iepsen, IT Specialist"
theme                   = "introduction"
enforce_ssl             = false
builddrafts             = false                             # Include pages with draft status of true
canonifyurls            = true                              # Turns relative urls into absolute urls
googleAnalytics       = "UA-53009932-1"

[params]    
    blogHead            = "Blog"                            # Full name shows on blog post pages
    firstName           = "Marcelo Iepsen"                    # First name shows in introduction on main page
    tagLine             = "I'm a Software Developer."           # Appears after the introduction
    introHeight         = "medium"                           # Input either 'medium' or 'large' or 'fullheight'
    themeStyle          = "light"                           # Choose 'light' or 'dark'
    avatar              = "img/profile.jpg"                 # Path to image in static folder eg. img/avatar.png, or comment out to remove
    email               = "marcelo@iepsen.com"             # Shows in contact section, or leave blank to omit
    localTime           = false                              # Show your current local time in contact section
    timeZone            = "America/Sao_Paulo"             # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateForm            = "Jan 2, 2006"
    dateFormFull        = "Mon Jan 2 2006 15:04:05 EST"
    cacheBuster         = false                             # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description         = "I'm a full-stack developer with 14+ years of experience in software development, software architecture and agile methodologies."             # Max 160 characters show in search results
    faviconFile         = "img/favicon.png"
    pygmentsStyle       = "monokai"                         # https://help.farbox.com/pygments.html
    pygmentsCodefences  = false
    footerText          = ""                                # Text to show in footer (overrides default text)
    fadeIn              = false                              # Turn on/off the fade-in effect
    customCSS           = ["css/custom.css"]                                # Include custom css files e.g. ["css/foo.css", "css/bar.css"]

    showBlog            = false                              # Show Blog section on home page
    showProjects        = true                              # Show Projects section on home page
    projectColumns      = "3"                               # Choose "2" or "3" columns for projects section
    placeHolderimg      = "/img/workday.jpg"                # For Projects without image
    showAllPosts        = false                             # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showLatest          = false                              # Show latest blog post summary
    shareButtons        = false                              # On post pages, show share this social buttons

    # Share buttons
    shareTwitter        = true
    shareFacebook       = true
    sharePinterest      = false
    shareGooglePlus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://linkedin.com/in/iepsen"
    icon = "linkedin"

[[params.social]]
    url = "https://facebook.com/iepsen"
    icon = "facebook"

[[params.social]]
    url = "https://twitter.com/iepsen"
    icon = "twitter"