baseurl = "https://iepsen.com/"
title = "Marcelo Iepsen"
theme = "coder-portfolio"
publishDir = "docs"
DefaultContentLanguage = "en"
paginate = 20
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
    author = "Marcelo Iepsen"
    description = "Senior Software Engineer"
    keywords = "developer,personal,ctv,smart tv"
    info = "Senior Software Engineer"
    avatarurl = "images/avatar.jpg"

    hideCredits = false
    hideCopyright = false

    snsShare = false

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/iepsen/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/iepsen/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/iepsen/"